# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv6_route.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv6_route.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10srv6_route.proto\"\x9a\x01\n\x10Seg6RouteRequest\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\x12+\n\x08segments\x18\x02 \x03(\x0b\x32\x19.Seg6RouteRequest.Segment\x12\x1b\n\x08seg6Mode\x18\x03 \x01(\x0e\x32\t.Seg6Mode\x12\x0b\n\x03\x64\x65v\x18\x04 \x01(\t\x1a\x1a\n\x07Segment\x12\x0f\n\x07segment\x18\x01 \x01(\t\" \n\x0eSeg6RouteReply\x12\x0e\n\x06status\x18\x01 \x01(\r\"\x14\n\x12ShowRoutes6Request\"\x12\n\x10ShowRoutes6Reply*!\n\x08Seg6Mode\x12\n\n\x06INLINE\x10\x00\x12\t\n\x05\x45NCAP\x10\x01\x32\xa5\x01\n\x0bSeg6Service\x12.\n\x08\x41\x64\x64Route\x12\x11.Seg6RouteRequest\x1a\x0f.Seg6RouteReply\x12\x31\n\x0bRemoveRoute\x12\x11.Seg6RouteRequest\x1a\x0f.Seg6RouteReply\x12\x33\n\tShowRoute\x12\x13.ShowRoutes6Request\x1a\x11.ShowRoutes6Replyb\x06proto3'
)

_SEG6MODE = _descriptor.EnumDescriptor(
  name='Seg6Mode',
  full_name='Seg6Mode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INLINE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENCAP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=253,
  serialized_end=286,
)
_sym_db.RegisterEnumDescriptor(_SEG6MODE)

Seg6Mode = enum_type_wrapper.EnumTypeWrapper(_SEG6MODE)
INLINE = 0
ENCAP = 1



_SEG6ROUTEREQUEST_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='Seg6RouteRequest.Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='Seg6RouteRequest.Segment.segment', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=175,
)

_SEG6ROUTEREQUEST = _descriptor.Descriptor(
  name='Seg6RouteRequest',
  full_name='Seg6RouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='destination', full_name='Seg6RouteRequest.destination', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segments', full_name='Seg6RouteRequest.segments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seg6Mode', full_name='Seg6RouteRequest.seg6Mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dev', full_name='Seg6RouteRequest.dev', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SEG6ROUTEREQUEST_SEGMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=175,
)


_SEG6ROUTEREPLY = _descriptor.Descriptor(
  name='Seg6RouteReply',
  full_name='Seg6RouteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Seg6RouteReply.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=209,
)


_SHOWROUTES6REQUEST = _descriptor.Descriptor(
  name='ShowRoutes6Request',
  full_name='ShowRoutes6Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=231,
)


_SHOWROUTES6REPLY = _descriptor.Descriptor(
  name='ShowRoutes6Reply',
  full_name='ShowRoutes6Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=251,
)

_SEG6ROUTEREQUEST_SEGMENT.containing_type = _SEG6ROUTEREQUEST
_SEG6ROUTEREQUEST.fields_by_name['segments'].message_type = _SEG6ROUTEREQUEST_SEGMENT
_SEG6ROUTEREQUEST.fields_by_name['seg6Mode'].enum_type = _SEG6MODE
DESCRIPTOR.message_types_by_name['Seg6RouteRequest'] = _SEG6ROUTEREQUEST
DESCRIPTOR.message_types_by_name['Seg6RouteReply'] = _SEG6ROUTEREPLY
DESCRIPTOR.message_types_by_name['ShowRoutes6Request'] = _SHOWROUTES6REQUEST
DESCRIPTOR.message_types_by_name['ShowRoutes6Reply'] = _SHOWROUTES6REPLY
DESCRIPTOR.enum_types_by_name['Seg6Mode'] = _SEG6MODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Seg6RouteRequest = _reflection.GeneratedProtocolMessageType('Seg6RouteRequest', (_message.Message,), {

  'Segment' : _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), {
    'DESCRIPTOR' : _SEG6ROUTEREQUEST_SEGMENT,
    '__module__' : 'srv6_route_pb2'
    # @@protoc_insertion_point(class_scope:Seg6RouteRequest.Segment)
    })
  ,
  'DESCRIPTOR' : _SEG6ROUTEREQUEST,
  '__module__' : 'srv6_route_pb2'
  # @@protoc_insertion_point(class_scope:Seg6RouteRequest)
  })
_sym_db.RegisterMessage(Seg6RouteRequest)
_sym_db.RegisterMessage(Seg6RouteRequest.Segment)

Seg6RouteReply = _reflection.GeneratedProtocolMessageType('Seg6RouteReply', (_message.Message,), {
  'DESCRIPTOR' : _SEG6ROUTEREPLY,
  '__module__' : 'srv6_route_pb2'
  # @@protoc_insertion_point(class_scope:Seg6RouteReply)
  })
_sym_db.RegisterMessage(Seg6RouteReply)

ShowRoutes6Request = _reflection.GeneratedProtocolMessageType('ShowRoutes6Request', (_message.Message,), {
  'DESCRIPTOR' : _SHOWROUTES6REQUEST,
  '__module__' : 'srv6_route_pb2'
  # @@protoc_insertion_point(class_scope:ShowRoutes6Request)
  })
_sym_db.RegisterMessage(ShowRoutes6Request)

ShowRoutes6Reply = _reflection.GeneratedProtocolMessageType('ShowRoutes6Reply', (_message.Message,), {
  'DESCRIPTOR' : _SHOWROUTES6REPLY,
  '__module__' : 'srv6_route_pb2'
  # @@protoc_insertion_point(class_scope:ShowRoutes6Reply)
  })
_sym_db.RegisterMessage(ShowRoutes6Reply)



_SEG6SERVICE = _descriptor.ServiceDescriptor(
  name='Seg6Service',
  full_name='Seg6Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=289,
  serialized_end=454,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddRoute',
    full_name='Seg6Service.AddRoute',
    index=0,
    containing_service=None,
    input_type=_SEG6ROUTEREQUEST,
    output_type=_SEG6ROUTEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveRoute',
    full_name='Seg6Service.RemoveRoute',
    index=1,
    containing_service=None,
    input_type=_SEG6ROUTEREQUEST,
    output_type=_SEG6ROUTEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ShowRoute',
    full_name='Seg6Service.ShowRoute',
    index=2,
    containing_service=None,
    input_type=_SHOWROUTES6REQUEST,
    output_type=_SHOWROUTES6REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEG6SERVICE)

DESCRIPTOR.services_by_name['Seg6Service'] = _SEG6SERVICE

# @@protoc_insertion_point(module_scope)
